"""Configuration settings"""

from .settings import (
    # Cache settings
    CACHE_DIR, CACHE_DB_PATH,
    # Modes
    DEFAULT_ANALYSIS_MODE, SUPPORTED_MODES,
    # Timeouts
    TIMEOUTS,
    # Performance caps
    MAX_ENRICH_VARIANTS_PER_ITEM, MAX_PAIRS_PER_CATEGORY,
    # Gemini API settings
    GEMINI_API_KEY, GEMINI_MODELS,
    # Rate limiting
    RATE_LIMIT_MIN_INTERVAL, RATE_LIMIT_MAX_RETRIES,
    RATE_LIMIT_BASE_SLEEP, RATE_LIMIT_ENRICHMENT_RETRIES,
    RATE_LIMIT_ENRICHMENT_BASE_SLEEP,
    # Matching thresholds
    MATCHING_THRESHOLDS, MATCH_TYPE_THRESHOLDS,
    # Scoring weights
    SCORING_WEIGHTS, HYBRID_WEIGHTS,
    # BM25 parameters
    BM25_K1, BM25_B,
    # Education/Experience processing
    DEGREE_KEYWORDS, ROLE_KEYWORDS, EDUCATION_CONNECTOR_KEYWORDS,
    EDUCATION_CONTEXT_KEYWORDS, INTERNSHIP_PROJECT_KEYWORDS,
    # Fit level thresholds
    FIT_LEVEL_THRESHOLDS,
    # Domain aliases
    TECH_ALIASES
)

__all__ = [
    'CACHE_DIR', 'CACHE_DB_PATH',
    'DEFAULT_ANALYSIS_MODE', 'SUPPORTED_MODES',
    'TIMEOUTS',
    'MAX_ENRICH_VARIANTS_PER_ITEM', 'MAX_PAIRS_PER_CATEGORY',
    'GEMINI_API_KEY', 'GEMINI_MODELS',
    'RATE_LIMIT_MIN_INTERVAL', 'RATE_LIMIT_MAX_RETRIES',
    'RATE_LIMIT_BASE_SLEEP', 'RATE_LIMIT_ENRICHMENT_RETRIES',
    'RATE_LIMIT_ENRICHMENT_BASE_SLEEP',
    'MATCHING_THRESHOLDS', 'MATCH_TYPE_THRESHOLDS',
    'SCORING_WEIGHTS', 'HYBRID_WEIGHTS',
    'BM25_K1', 'BM25_B',
    'DEGREE_KEYWORDS', 'ROLE_KEYWORDS', 'EDUCATION_CONNECTOR_KEYWORDS',
    'EDUCATION_CONTEXT_KEYWORDS', 'INTERNSHIP_PROJECT_KEYWORDS',
    'FIT_LEVEL_THRESHOLDS',
    'TECH_ALIASES'
]

